import type { ScheduleBlock } from "./types"

export function getInitialSchedule(): ScheduleBlock[] {
  return [
    {
      id: "b1",
      startTime: "07:00",
      endTime: "07:30",
      title: "晨起养生",
      category: "rest",
      details: ["温水一杯 (200ml)", "5 分钟晨间拉伸", "测量血压并记录"],
      aiGenerated: true,
    },
    {
      id: "b2",
      startTime: "07:30",
      endTime: "08:00",
      title: "低盐营养早餐",
      category: "meal",
      details: ["燕麦粥 (无糖)", "水煮蛋 1 个", "凉拌芹菜丝"],
      aiGenerated: true,
    },
    {
      id: "b3",
      startTime: "08:00",
      endTime: "08:15",
      title: "晨间用药",
      category: "medication",
      details: ["氨氯地平 5mg x1", "阿托伐他汀 20mg x1"],
      aiGenerated: true,
    },
    {
      id: "b4",
      startTime: "09:30",
      endTime: "10:00",
      title: "户外快走 30 分钟",
      category: "exercise",
      details: ["中等强度", "心率控制 100-120", "避免空腹运动"],
      aiGenerated: true,
    },
    {
      id: "b5",
      startTime: "10:15",
      endTime: "10:30",
      title: "上午加餐",
      category: "meal",
      details: ["低糖酸奶 1 杯", "坚果一小把 (15g)"],
      aiGenerated: true,
    },
    {
      id: "b6",
      startTime: "12:00",
      endTime: "12:45",
      title: "低嘌呤午餐",
      category: "meal",
      details: ["清蒸鸡胸肉", "蒜蓉西兰花", "紫米饭 (小碗)"],
      aiGenerated: true,
    },
    {
      id: "b7",
      startTime: "13:00",
      endTime: "13:30",
      title: "午间小憩",
      category: "rest",
      details: ["闭目养神 20-30 分钟", "避免趴睡", "设置闹钟"],
      aiGenerated: true,
    },
    {
      id: "b8",
      startTime: "15:30",
      endTime: "15:45",
      title: "下午茶歇",
      category: "meal",
      details: ["苹果 1 个", "菊花枸杞茶"],
      aiGenerated: true,
    },
    {
      id: "b9",
      startTime: "16:00",
      endTime: "16:30",
      title: "八段锦练习",
      category: "exercise",
      details: ["完整一套约 25 分钟", "注意呼吸配合", "量力而行"],
      aiGenerated: true,
    },
    {
      id: "b10",
      startTime: "18:00",
      endTime: "18:45",
      title: "清淡晚餐",
      category: "meal",
      details: ["蔬菜豆腐汤", "清炒时蔬", "杂粮馒头半个"],
      aiGenerated: true,
    },
    {
      id: "b11",
      startTime: "19:30",
      endTime: "20:00",
      title: "饭后散步",
      category: "exercise",
      details: ["缓步走 20-30 分钟", "有助于餐后血糖控制"],
      aiGenerated: true,
    },
    {
      id: "b12",
      startTime: "21:00",
      endTime: "21:15",
      title: "晚间用药 & 复测血压",
      category: "medication",
      details: ["氨氯地平 5mg (如医嘱)", "记录晚间血压数值"],
      aiGenerated: true,
    },
    {
      id: "b13",
      startTime: "21:30",
      endTime: "22:00",
      title: "助眠放松",
      category: "rest",
      details: ["热水泡脚 15 分钟", "腹式深呼吸 5 分钟", "避免看手机"],
      aiGenerated: true,
    },
  ]
}
