import { HealthEvent } from "./types"

export const initialEvents: HealthEvent[] = [
  {
    id: "1",
    title: "流行性感冒",
    status: "recovered",
    startDate: "2025-11-01",
    resolvedDate: "2025-11-10",
    symptoms: ["发烧 39\u00b0C", "咳嗽", "头痛", "全身酸痛"],
    medications: ["布洛芬", "复方氨酚烷胺"],
    diagnosis: "甲型流感",
    aiGenerated: false,
    aiAdvice: undefined,
    timeline: [
      { id: "1a", date: "2025-11-01", description: "出现发烧症状，体温 39\u00b0C" },
      { id: "1b", date: "2025-11-02", description: "开始服用布洛芬退烧" },
      { id: "1c", date: "2025-11-03", description: "前往医院就诊，确认甲型流感" },
      { id: "1d", date: "2025-11-05", description: "体温恢复正常，仍有轻微咳嗽" },
      { id: "1e", date: "2025-11-10", description: "症状完全消失，康复" },
    ],
    resolution: "已停药，完全康复",
  },
  {
    id: "2",
    title: "慢性胃炎复发",
    status: "active",
    startDate: "2026-02-15",
    nextFollowUp: "2026-03-20",
    symptoms: ["上腹隐痛", "餐后饱胀", "反酸"],
    medications: ["奥美拉唑", "铝碳酸镁"],
    diagnosis: "慢性浅表性胃炎",
    aiGenerated: true,
    aiAdvice: "建议清淡饮食，避免辛辣刺激食物；按时服药，疗程 4 周后复查胃镜；注意饮食规律，避免暴饮暴食。",
    timeline: [
      { id: "2a", date: "2026-02-15", description: "进食火锅后出现上腹隐痛" },
      { id: "2b", date: "2026-02-17", description: "症状持续，开始服用奥美拉唑" },
      { id: "2c", date: "2026-02-20", description: "就医胃镜检查，确诊浅表性胃炎" },
      { id: "2d", date: "2026-03-01", description: "症状有所缓解，继续服药观察" },
    ],
  },
  {
    id: "3",
    title: "腰椎间盘突出",
    status: "active",
    startDate: "2026-01-10",
    nextFollowUp: "2026-04-10",
    symptoms: ["腰部疼痛", "左腿放射痛", "久坐后加重"],
    medications: ["塞来昔布", "甲钴胺"],
    diagnosis: "L4-L5 椎间盘突出",
    aiGenerated: false,
    aiAdvice: "建议避免久坐和弯腰负重；坚持核心肌群训练；疼痛加重时及时复诊。",
    timeline: [
      { id: "3a", date: "2026-01-10", description: "搬重物后出现急性腰痛" },
      { id: "3b", date: "2026-01-12", description: "就医 MRI 检查，确诊腰椎间盘突出" },
      { id: "3c", date: "2026-01-15", description: "开始保守治疗+物理康复" },
      { id: "3d", date: "2026-02-01", description: "疼痛减轻约 50%，继续康复训练" },
      { id: "3e", date: "2026-03-01", description: "日常活动基本不受限，仍需注意" },
    ],
  },
  {
    id: "4",
    title: "过敏性皮炎",
    status: "recovered",
    startDate: "2025-09-05",
    resolvedDate: "2025-09-20",
    symptoms: ["皮肤红疹", "瘙痒", "局部肿胀"],
    medications: ["氯雷他定", "炉甘石洗剂"],
    diagnosis: "接触性过敏性皮炎",
    aiGenerated: true,
    aiAdvice: "已确认为接触新洗涤剂引起的过敏反应，建议今后避免使用含该成分的产品。",
    timeline: [
      { id: "4a", date: "2025-09-05", description: "手臂出现红疹伴瘙痒" },
      { id: "4b", date: "2025-09-07", description: "就医皮肤科，确诊接触性皮炎" },
      { id: "4c", date: "2025-09-10", description: "更换洗涤剂，开始服用抗过敏药" },
      { id: "4d", date: "2025-09-20", description: "皮疹完全消退" },
    ],
    resolution: "已停药，避免过敏原后未复发",
  },
  {
    id: "5",
    title: "高血压波动",
    status: "active",
    startDate: "2026-03-01",
    nextFollowUp: "2026-03-15",
    symptoms: ["晨起头晕", "血压偏高 (150/95)"],
    medications: ["氨氯地平"],
    diagnosis: "原发性高血压 II 级",
    aiGenerated: true,
    aiAdvice: "近期血压控制不理想，建议每日晨起监测血压并记录；控制钠盐摄入；按时服药，下次复诊讨论是否调整用药。",
    timeline: [
      { id: "5a", date: "2026-03-01", description: "晨起感觉头晕，测血压 150/95 mmHg" },
      { id: "5b", date: "2026-03-02", description: "与 AI 助手对话，记录血压数据" },
      { id: "5c", date: "2026-03-03", description: "血压仍偏高 145/92，继续监测中" },
    ],
  },
]
